### ISSUE TITLE
ハンズオン手順について

### ISSUE THREAD

**Issue by matsuyama-0207** [IBMDeveloperTokyo/openshift-s2i-lab#1]
ハンズオンは問題なく進めましたが、念のため、気づいた点をご報告します。

①
Webhookのところで、

> 入力後、以下の図の様に緑のチェックマークが付いたら設定成功です。 

とありましたが、「Add webhook」ボタンクリック後、
以下のような表示になりました。
![image](https://user-images.githubusercontent.com/61312158/118745236-b667f600-b890-11eb-928d-b7ea17ab3a1d.png)

②
ソースコードを変更するところで、
> ここでは23行目の英文「Example Health」を日本語の「医療管理」に変更してみます。

とありますが、元々のソースコードが「Example Health」ではなく「健康管理」で、画面キャプチャも「健康管理」になっておりました。

以上です。よろしくお願いいたします。

**Comment by AHA04300** [comment]
①は手順アップデートしました。（commit：b54fb3c92d7929cc0910594f45bace5bd4a8c824）

②はソースコードが修正されていることを確認しました。
